//
//  FirstScreenProtocols.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

// MARK: - Navigation Option
enum FirstScreenNavigationOption {
    /**
     - example usage
     */
}

// MARK: - Presenter -> View
protocol FirstScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
}

// MARK: - View -> Presenter
protocol FirstScreenViewToPresenterProtocol: AnyObject {
    func started()
}

// MARK: - Interactor -> Presenter
protocol FirstScreenInterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol FirstScreenPresentorToInterectorProtocol: AnyObject {
    
}

// MARK: - Presenter -> Router or WireFrame
protocol FirstScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigate(to option: FirstScreenNavigationOption)
}


