//
//  FirstScreenViewController.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class FirstScreenViewController: UIViewController {
    
    // MARK: Delegate initialization
    var presenter: FirstScreenViewToPresenterProtocol?
    
    // MARK: Outlets
    
    
    // MARK: Custom initializers go here
    var label: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        label.text = "First Screen"
        label.textColor = .black
        label.textAlignment = .center
        label.font = UIFont.preferredFont(forTextStyle: .body)
        return label
    }()
    
    // MARK: View Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }
    
    // MARK: User Interaction - Actions & Targets
    
    
    // MARK: Additional Helpers
    
}

// MARK: - Extension
/**
 - Documentation for purpose of extension
 */
extension FirstScreenViewController {
    
}

// MARK: - Presenter to View
extension FirstScreenViewController: FirstScreenPresenterToViewProtocl {
    
    func initialControlSetup() {
        self.view.backgroundColor = .white
        self.view.addSubview(label)
        label.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        label.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        label.heightAnchor.constraint(equalToConstant: 45).isActive = true
        label.widthAnchor.constraint(equalToConstant: 200).isActive = true
    }
    
}
