//
//  FirstScreenRouter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import UIKit
import Foundation

class FirstScreenRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "FirstScreen", bundle: nil)
    
    // MARK: Module Setup
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: FirstScreenViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = FirstScreenInteractor()
        let presenter = FirstScreenPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension FirstScreenRouter: FirstScreenPresenterToRouterProtocol {
    
    func navigate(to option: FirstScreenNavigationOption) {
        // ...
    }
    
}
