//
//  FirstScreenPresenter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class FirstScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: FirstScreenPresenterToViewProtocl
    private var interactor: FirstScreenPresentorToInterectorProtocol
    private var router: FirstScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: FirstScreenPresenterToViewProtocl, interactor: FirstScreenPresentorToInterectorProtocol, router: FirstScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension FirstScreenPresenter: FirstScreenViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension FirstScreenPresenter: FirstScreenInterectorToPresenterProtocol {
    
}

