//
//  SecondScreenProtocols.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

// MARK: - Navigation Option
enum NavigationOption {
    /**
     - example usage
     */
    case login
    case register
}

// MARK: - Presenter -> View
protocol SecondScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
}

// MARK: - View -> Presenter
protocol SecondScreenViewToPresenterProtocol: AnyObject {
    func started()
    func getData()
}

// MARK: - Interactor -> Presenter
protocol SecondScreenInterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol SecondScreenPresentorToInterectorProtocol: AnyObject {
    func apiCall()
}

// MARK: - Presenter -> Router or WireFrame
protocol SecondScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigate(to option: NavigationOption)
}


