//
//  SecondScreenPresenter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class SecondScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: SecondScreenPresenterToViewProtocl
    private var interactor: SecondScreenPresentorToInterectorProtocol
    private var router: SecondScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: SecondScreenPresenterToViewProtocl, interactor: SecondScreenPresentorToInterectorProtocol, router: SecondScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension SecondScreenPresenter: SecondScreenViewToPresenterProtocol {
    
    func getData() {
        interactor.apiCall()
    }
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension SecondScreenPresenter: SecondScreenInterectorToPresenterProtocol {

}

