//
//  ThirdScreenInteractor.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation

class ThirdScreenInteractor {
    
    // MARK: Delegate initialization
    var presenter: ThirdScreenInterectorToPresenterProtocol?
    
    // MARK: - Call Service
    
}

// MARK: - Presenter to Interactor
extension ThirdScreenInteractor: ThirdScreenPresentorToInterectorProtocol {
    
}
