//
//  ThirdScreenProtocols.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

// MARK: - Navigation Option
enum ThirdScreenNavigationOption {
    /**
     - example usage
     */
}

// MARK: - Presenter -> View
protocol ThirdScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
}

// MARK: - View -> Presenter
protocol ThirdScreenViewToPresenterProtocol: AnyObject {
    func started()
}

// MARK: - Interactor -> Presenter
protocol ThirdScreenInterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol ThirdScreenPresentorToInterectorProtocol: AnyObject {
    
}

// MARK: - Presenter -> Router or WireFrame
protocol ThirdScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigate(to option: ThirdScreenNavigationOption)
}


