//
//  ThirdScreenPresenter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class ThirdScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: ThirdScreenPresenterToViewProtocl
    private var interactor: ThirdScreenPresentorToInterectorProtocol
    private var router: ThirdScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: ThirdScreenPresenterToViewProtocl, interactor: ThirdScreenPresentorToInterectorProtocol, router: ThirdScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension ThirdScreenPresenter: ThirdScreenViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension ThirdScreenPresenter: ThirdScreenInterectorToPresenterProtocol {
    
}

