//
//  FourthScreenEntity.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 23/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
