//
//  HomeScreenProtocols.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

// MARK: - Navigation Option
enum HomeScreenNavigationOption {
    case first
    case second
}

// MARK: - Presenter -> View
protocol HomeScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
}

// MARK: - View -> Presenter
protocol HomeScreenViewToPresenterProtocol: AnyObject {
    func started()
    func firstBtnClicked()
    func secondBtnClicked()
}

// MARK: - Interactor -> Presenter
protocol HomeScreenInterectorToPresenterProtocol: AnyObject {
    func success()
    func fail()
}

// MARK: - Presenter -> Interactor
protocol HomeScreenPresentorToInterectorProtocol: AnyObject {
    
}

// MARK: - Presenter -> Router or WireFrame
protocol HomeScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigate(to option: HomeScreenNavigationOption)
}
