//
//  HomeScreenRouter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import UIKit
import Foundation

class HomeScreenRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "HomeScreen", bundle: nil)
    
    // MARK: Module Setup
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: HomeScreenViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = HomeScreenInteractor()
        let presenter = HomeScreenPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension HomeScreenRouter: HomeScreenPresenterToRouterProtocol {
    
    func navigate(to option: HomeScreenNavigationOption) {
        switch option {
        case .first:
            firstScreen()
        case .second:
            secondScreen()
        }
    }
    
    private func firstScreen() {
        let firstRouter = FirstScreenRouter()
        navigationController?.pushView(firstRouter)
    }
    
    private func secondScreen() {
        let secondRouter = SecondScreenRouter()
        let routerNavigationController = BaseNavigatinController(router: secondRouter)
        routerNavigationController.modalPresentationStyle = .fullScreen
        navigationController?.present(routerNavigationController, animated: true, completion: nil)
    }
    
}
