//
//  HomeScreenPresenter.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class HomeScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: HomeScreenPresenterToViewProtocl
    private var interactor: HomeScreenPresentorToInterectorProtocol
    private var router: HomeScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: HomeScreenPresenterToViewProtocl, interactor: HomeScreenPresentorToInterectorProtocol, router: HomeScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension HomeScreenPresenter: HomeScreenViewToPresenterProtocol {
    
    func firstBtnClicked() {
        router.navigate(to: .first)
    }
    
    func secondBtnClicked() {
        router.navigate(to: .second)
    }
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension HomeScreenPresenter: HomeScreenInterectorToPresenterProtocol {
   
    func success() {
        router.showAlert(with: "Success", message: "is Working Fine")
    }
    
    func fail() {
        router.showAlert(with: "Fail", message: "Please fix it")
    }
    
}

