//
//  HomeScreenViewController.swift
//  ViperTest
//
//  Created Zin Lin Htet Naing on 16/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class HomeScreenViewController: UIViewController {
    
    // MARK: Delegate initialization
    var presenter: HomeScreenViewToPresenterProtocol?
    
    // MARK: Outlets
    @IBOutlet weak var firstButton: UIButton!
    @IBOutlet weak var secondButton: UIButton!
    
    // MARK: Custom initializers go here
    
    
    // MARK: View Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }
    
    // MARK: User Interaction - Actions & Targets
    @IBAction func firstButtonAction(_ sender: UIButton) {
        presenter?.firstBtnClicked()
    }
    
    @IBAction func secondButtonAction(_ sender: UIButton) {
        presenter?.secondBtnClicked()
    }
    
    // MARK: Additional Helpers
    
}

// MARK: - Extension
/**
 - Documentation for purpose of extension
 */
extension HomeScreenViewController {
    
}

// MARK: - Presenter to View
extension HomeScreenViewController: HomeScreenPresenterToViewProtocl {
    
    func initialControlSetup() {
        self.view.backgroundColor = .white
    }
    
}
